module.exports = [
  { _id: '57f42ab654177375f8995deb',
    updatedBy: '57f2a1d5ad9c4c1b357c31fe',
    updatedAt: '2016-10-04T22:18:41.498Z',
    createdBy: '57f2a1d5ad9c4c1b357c31fe',
    createdAt: '2016-10-04T22:18:30.495Z',
    slug: 'shy-boys',
    press_email: '',
    booking_email: '',
    bio: '<p>blah blah blah</p>',
    name: 'Shy Boys',
    members: [ '57f2a1d5ad9c4c1b357c31fe' ],
    __v: 1,
    photos: [],
    active: true,
    highDive: true },
  { _id: '57f44492b17c1b84d73cbe3d',
    updatedAt: '2016-10-05T00:08:50.733Z',
    createdAt: '2016-10-05T00:08:50.733Z',
    slug: 'berwanger',
    name: 'Berwanger',
    members: [],
    __v: 0,
    photos: [],
    active: true,
    highDive: false },
  { _id: '57f44492b17c1b84d73cbe3e',
    updatedAt: '2016-10-05T00:08:50.737Z',
    createdAt: '2016-10-05T00:08:50.737Z',
    slug: 'bummer',
    name: 'Bummer',
    members: [],
    __v: 0,
    photos: [],
    active: true,
    highDive: false },
  { _id: '57f44492b17c1b84d73cbe3f',
    updatedAt: '2016-10-05T00:08:50.740Z',
    createdAt: '2016-10-05T00:08:50.740Z',
    slug: 'the-conquerors',
    name: 'The Conquerors',
    members: [],
    __v: 0,
    photos: [],
    active: true,
    highDive: false },
  { _id: '57f44492b17c1b84d73cbe41',
    updatedAt: '2016-10-05T00:08:50.748Z',
    createdAt: '2016-10-05T00:08:50.748Z',
    slug: 'psychic-heat',
    name: 'Psychic Heat',
    members: [],
    __v: 0,
    photos: [],
    active: true,
    highDive: false },
  { _id: '57f44492b17c1b84d73cbe42',
    updatedAt: '2016-10-05T00:08:50.750Z',
    createdAt: '2016-10-05T00:08:50.750Z',
    slug: 'rooftop-vigilantes',
    name: 'Rooftop Vigilantes',
    members: [],
    __v: 0,
    photos: [],
    active: true,
    highDive: false },
  { _id: '57f44492b17c1b84d73cbe43',
    updatedAt: '2016-10-05T00:08:50.753Z',
    createdAt: '2016-10-05T00:08:50.753Z',
    slug: 'sex-snobs',
    name: 'Sex Snobs',
    members: [],
    __v: 0,
    photos: [],
    active: true,
    highDive: false },
  { _id: '57f44492b17c1b84d73cbe45',
    updatedAt: '2016-10-05T00:08:50.759Z',
    createdAt: '2016-10-05T00:08:50.759Z',
    slug: 'snacky',
    name: 'Snacky',
    members: [],
    __v: 0,
    photos: [],
    active: true,
    highDive: false },
  { _id: '57f44492b17c1b84d73cbe40',
    updatedAt: '2016-10-11T20:50:27.801Z',
    createdAt: '2016-10-05T00:08:50.745Z',
    slug: 'fullbloods',
    name: 'Fullbloods',
    members: [ '57f44492b17c1b84d73cbe3c' ],
    __v: 4,
    bio: '<p style="box-sizing: border-box; margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; line-height: 2; color: #5f6062; font-family: \'Open Sans\', sans-serif;">Ross Brown is an unassuming young Midwesterner who leads a group of fellow unassuming Midwesterners in a pop band called Fullbloods. &ldquo;We&rsquo;re a boring band with no story,&rdquo; Brown says.</p>\r\n<p style="box-sizing: border-box; margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; line-height: 2; color: #5f6062; font-family: \'Open Sans\', sans-serif;">Well &mdash; maybe the story is the songs. By that metric, Mild West, the second full-length from the band (and first on Kansas City label High Dive Records), is a saga, stacked from top to bottom with melodic songwriting and dazzling production.</p>\r\n<p style="box-sizing: border-box; margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; line-height: 2; color: #5f6062; font-family: \'Open Sans\', sans-serif;">It&rsquo;s the destiny of many sonically curious, production-minded musicians to come under the spell of Steely Dan, the patron saints of studio wizardry. Brown&mdash; a guy who&rsquo;s happier demoing experimental tracks in his basement cave than performing for the beery local masses &mdash; is of this tribe, and Mild West is him swinging for those fences.</p>\r\n<p style="box-sizing: border-box; margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; line-height: 2; color: #5f6062; font-family: \'Open Sans\', sans-serif;">&ldquo;We wanted to achieve the qualities of hi-fi late &lsquo;70s hits,&rdquo; Brown says of the creation of Mild West. &ldquo;We came up with some reference material &mdash; Dire Straits, Boz Scaggs, Teddy Pendergrass, Wings, Fleetwood Mac, and the ineffable Steely Dan &mdash; and did a lot of intense listening. It&rsquo;s arguably our favorite part of being a band.&rdquo;</p>\r\n<p style="box-sizing: border-box; margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; line-height: 2; color: #5f6062; font-family: \'Open Sans\', sans-serif;">Fullbloods point their flashlights in those satiny corners on parts of Mild West. Fans of Donald Fagen&rsquo;s quiet jazz-pop masterpiece The Nightfly will find much to love about tracks like &ldquo;Neverminded,&rdquo; &ldquo;New Generation&rdquo; and &ldquo;Shrimp Etouffee.&rdquo; But Mild West is hardly revivalism. Elsewhere there are more modern influences, like Richard Swift and Real Estate &mdash; exceptional songwriters who put a lot of thought into making their records sound beautiful.</p>\r\n<p style="box-sizing: border-box; margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; line-height: 2; color: #5f6062; font-family: \'Open Sans\', sans-serif;">Even that doesn&rsquo;t capture the album, though. There is believable funk present. There&rsquo;s also an experimental streak running through Mild West. This is a wild album, with unexpected flourishes throughout. It&rsquo;s easy listening for weirdos, for people who like to be surprised by the music they listen to.</p>\r\n<p style="box-sizing: border-box; margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; line-height: 2; color: #5f6062; font-family: \'Open Sans\', sans-serif;">&ldquo;Caught a feeling,&rdquo; Brown sings halfway through the album. &ldquo;Made it mine.&rdquo;</p>\r\n<p style="box-sizing: border-box; margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; line-height: 2; color: #5f6062; font-family: \'Open Sans\', sans-serif;">This record is a feeling &mdash; lots of feelings, actually. You ought to make them yours.</p>\r\n<p style="box-sizing: border-box; margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; line-height: 2; color: #5f6062; font-family: \'Open Sans\', sans-serif;">Fullbloods are: Ross Brown; Jared Tomasino; David Seume; and Bill Pollock. Mild West was engineered by Mike Nolte (Starfucker, Of Montreal).</p>',
    booking_email: '',
    press_email: '',
    updatedBy: '57f2a1d5ad9c4c1b357c31fe',
    notes: '',
    website: '',
    audioPlayerEmbed: '<iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/86662207&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>',
    social:
     { bandcamp: 'http://bandcamp.com/fullbloods',
       facebook: 'http://facebook.com/fullbloods',
       instagram: 'fullbloods.mp3',
       soundcloud: '',
       twitter: 'fullbloods' },
    location:
     { country: null,
       postcode: null,
       state: null,
       street1: null,
       suburb: null },
    photos: [],
    active: true,
    highDive: true } ]
